llm:
  url: ""
  waitBeforeFallbackTrigger: 5000
  keywordToStaticIdMap:
    MESH: 2
    VOIP: 3
    CUJO: 5

fallback:
  dataIdToIntelligenceFallbackResponseMap:
    data1:
      - 3
      - 5
      - 2
    data2:
      - 9
      - 8



spring:
  application:
    name=quant-parent: