llm:
  url: ""
  waitBeforeFallbackTrigger: 5000
  keywordToStaticIdMap:
    MESH: 1
    VOIP: 2
    CUJO: 3

fallback:
  dataIdToIntelligenceFallbackResponseMap:
    data1:
      - 3
      - 5
      - 7
      - 6
    data2:
      - 9
      - 8



spring:
  application:
    name=quant-parent: